spring.application.name=FitMark
spring.datasource.url=jdbc:postgresql://localhost:5432/API
spring.datasource.username=postgres
spring.datasource.password=283997

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
